### ISSUE TITLE
Configure GitHub to set 'master' as the default branch

### ISSUE THREAD

**Issue by dolmen** [b97tsk/rx#1]
The default branch on GitHub is `main`.
But all the code is on branch `master`.

Result: the repository appears to be almost empty... until we manually select the `master` branch.

**Comment by dolmen** [comment]
Apparently `master` has been now renamed to `main`, so there is no more issue.

**Comment by b97tsk** [comment]
Development moved to `generics` branch.

`master` branch has been abandoned. Early commits can be found by tags though.
